[url]
rpc = "https://eth-mainnet.g.alchemy.com/v2/"
block_explorer = "https://api.etherscan.io/api/"
localhost = "http://127.0.0.1:8545/"

[routers]
uniswapv2 = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
uniswapv3 = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
sushiswap = "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"

[tokens]
usdc = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
usdt = "0xdac17f958d2ee523a2206206994597c13d831ec7"
weth = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"